version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./build/api
    depends_on:
      - vcpkg

  test_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./build/test_api
    depends_on:
      - vcpkg

  vcpkg:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/true

volumes:
  build_data:
